services:
    tee:
        command: ["sh", "-c", "pnpm start & pnpm client start & wait"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
        environment:
            - .env
        ports:
            - "4173:80"
            - "3000:3000"
            - ""
        restart: always

volumes:
    tee:
