services:
    tee:
        command: ["sh", "-c", "pnpm start --character=/app/characters/fleek.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
        env_file:
            - .env
        ports:
            - "4173:80"
            - "3000:3000"
        restart: always
        deploy:
            resources:
                limits:
                    memory: "3G"
                    cpus: "1.8"

volumes:
    tee:
